name: Build OpenOS Arch ISO

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Arch Linux Live ISO
        uses: cytopia/docker-archiso@master
        with:
          config: |
            # Archiso custom build configuration
            iso_name="openos-arch"
            iso_version="1.0.0"
            install_dir="arch"

      - name: Upload ISO as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenOS-Arch-ISO
          path: |
            out/*.iso
